package datasrv_inject

import (
	"github.com/shopspring/decimal"
)

// Pg version
// 20241111: Change filter state to completed only
const dbQueryForSeasonTotalRewards = `select season_id,
       target_user_wallet,
       sum(asset_amount::Decimal(20, 8)) as season_total,
       seasons.name      as season_name,
       seasons.idx       as season_idx
from applications
         join seasons on season_id = seasons.id
where applications.type = 'NEW_REWARD'
  and applications.asset_name = 'SCR'
  and applications.state in ('completed')
  and applications.sub_type IN (NULL ,'')
GROUP by season_id, target_user_wallet, seasons.name, season_idx`

const MetaforoTotalCreditRatio = "0.05"

// AggregatedSeasonCredit saves scores aggregated by seasons
type AggregatedSeasonCredit struct {
	SeasonId         uint
	TargetUserWallet string
	SeasonTotal      decimal.Decimal
	SeasonName       string
	SeasonIdx        uint
}

type UserCreditRecord struct {
	TargetUserWallet string

	SeasonsCredit map[uint]AggregatedSeasonCredit

	SeedCount int

	MetaforoVoteCount        int
	MetaforoVoteRewardCredit decimal.Decimal

	CurrentSeasonCredit       decimal.Decimal // Credits should be issued in current season
	WeightedPastSeasonsCredit decimal.Decimal // Weighted past seasons credit
	TotalSeasonCredit         decimal.Decimal // Sum of all seasons credit
}

type NodeCalcResponse struct {
	// Summarized credits data
	SeasonName                   string `json:"season_name"`
	SeasonTotalCreditWithoutMint string `json:"season_total_credit_without_mint"`
	SeasonTotalMintCredit        string `json:"season_total_mint_credit"`
	TotalWalletCount             int    `json:"total_wallet_count"`
	ActivateWalletCount          int    `json:"activate_wallet_count"`

	// Some flags
	MintRewardConfirmed bool `json:"metaforo_confirmed"`
	SeedSnapshoted      bool `json:"seed_snapshoted"`

	// Credit detail records
	Records []*CreditDetail `json:"records"`
}

// CreditDetail saves result of credit calculations, here are the formula
// * SeasonsCredit: Individual credit record for each season
// * SeasonTotalCredit: Sum all seasons credit directly
// * MetaforoCredit: Credits gained by Metaforo vote, metaforoVoteUnit * voteCount
// * ActivityCredit: Current season credit plus metaforo vote credit
// * EffectiveCredit: Activity credit plus weighted post seasons credits
// * SeedCount: Seed count fetched from indexer API
type CreditDetail struct {
	Wallet            string                 `json:"wallet"`
	SeasonsCredit     []SeasonCreditResponse `json:"seasons_credit"`
	SeasonTotalCredit string                 `json:"season_total_credit"`
	ActivityCredit    string                 `json:"activity_credit"`
	MetaforoVoteCount int                    `json:"metaforo_vote_count"`
	MetaforoCredit    string                 `json:"metaforo_credit"`
	SeedCount         int                    `json:"seed_count"`
	EffectiveCredit   string                 `json:"effective_credit"`
}

type SeasonCreditResponse struct {
	SeasonIdx  uint   `json:"season_idx"`
	SeasonName string `json:"season_name"`
	Total      string `json:"total"`
}

type UpdateMetaforoVoteDataRequest struct {
	SeasonIdx int `json:"season_idx"`

	// If season has already calculated vote data, the vote data will only be updated when force flag is true
	Force bool `json:"force"`

	// RawCsvData saves csv data generated by parser, will be split and handled in function
	RawCsvData string `json:"raw_csv_data"`
}

type MetaforoMintRecord struct {
	Wallet    string `json:"address"`
	VoteCount int    `json:"vote"`
	Name      string `json:"name"`
}

type MintResult struct {
	TotalSeasonCreditWithoutMint decimal.Decimal
	TotalMetaforoCredits         decimal.Decimal
	UserCredits                  map[string]UserCreditRecord
	ActivateWalletCount          int
	DetailRecords                []*CreditDetail
	MintRewardData               map[string]string
}

const (
	getCurrentSeasonMintableUserVoteRecordsQuery = `SELECT * FROM proposal_user_vote_records
		WHERE proposal_id IN (SELECT id FROM proposals p WHERE vote_gate_id =
			(SELECT id FROM proposal_vote_gates WHERE season_id = ? AND name like '节点%')
			AND state in (6, 7, 9) AND p.version = (select max(version) from proposals p2 where p.proposal_record_id=p2.proposal_record_id));`
)
