package data_srv

import "github.com/gin-gonic/gin"

type UpdateMetaforoVoteDataRequest struct {
	SeasonIdx int `json:"season_idx"`

	// If season has already calculated vote data, the vote data will only be updated when force flag is true
	Force bool `json:"force"`

	// RawCsvData saves csv data generated by parser, will be split and handled in function
	RawCsvData string `json:"raw_csv_data"`
}

func UpdateMetaforoVoteData(ctx *gin.Context) {

}
