package data_srv

import (
	"fmt"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	"github.com/rs/zerolog/log"
	"github.com/theseed-labs/os-backend/internal/api"
	"github.com/theseed-labs/os-backend/internal/api/proposal"
	"github.com/theseed-labs/os-backend/internal/sdk"
)

type UpdateMetaforoVoteDataRequest struct {
	SeasonIdx int `json:"season_idx"`

	// If season has already calculated vote data, the vote data will only be updated when force flag is true
	Force bool `json:"force"`

	// RawCsvData saves csv data generated by parser, will be split and handled in function
	RawCsvData string `json:"raw_csv_data"`
}

type MetaforoMintRecord struct {
	Wallet    string `json:"address"`
	VoteCount int    `json:"vote"`
	Name      string `json:"name"`
}

func FetchSingleProposalUserVoteRecord(ctx *gin.Context) {
	db, cfg := api.ForContextDBAndConfig(ctx)

	proposalId, err := strconv.ParseUint(ctx.Param("proposal_id"), 10, 64)
	if err != nil {
		log.Error().Msgf("parse proposal id error: %+v", err)
		sdk.LogServerErrorToSentry(ctx, err)
		ctx.JSON(http.StatusBadRequest, api.BadRequest(fmt.Errorf("parse proposal id error: %+v", err)))
		return
	}

	err = proposal.UpdateUserVoteRecordViaMetaforo(db, cfg.MetaforoData.GroupName, uint(proposalId))
	if err != nil {
		log.Error().Msgf("update user vote record via metaforo error: %+v", err)
		sdk.LogServerErrorToSentry(ctx, err)
		ctx.JSON(http.StatusInternalServerError, api.BadRequest(fmt.Errorf("update user vote record via metaforo error: %+v", err)))
		return
	}

	ctx.JSON(http.StatusOK, gin.H{"success": true})
}
