package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/samber/lo"
	"github.com/theseed-labs/os-backend/internal/api"
	"github.com/theseed-labs/os-backend/internal/graph/gmodel"
	"github.com/theseed-labs/os-backend/internal/model"
)

// AvailableGuilds is the resolver for the availableGuilds field.
func (r *queryResolver) AvailableGuilds(ctx context.Context) ([]*gmodel.Guild, error) {
	ginCtx, err := api.GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}

	user, enforcer, db, _ := api.ForContext(ginCtx)

	ok, err := enforcer.HasRoleForUser(user.Wallet, api.RoleHall)
	if err != nil {
		return nil, err
	}

	var guilds []*model.Guild

	if ok {
		guilds, _, err = model.GuildModel.List(db, nil)
		if err != nil {
			return nil, err
		}
	} else {
		guilds, _, err = model.GuildModel.ListBySponsor(db, user.Wallet, nil)
		if err != nil {
			return nil, err
		}
	}

	return lo.Map(guilds, func(g *model.Guild, _ int) *gmodel.Guild {
		return &gmodel.Guild{
			ID:    int(g.ID),
			Logo:  g.Logo,
			Name:  g.Name,
			Intro: g.Intro,
			Desc:  g.Desc,
		}
	}), nil
}
