package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/samber/lo"
	"github.com/theseed-labs/os-backend/internal/api"
	"github.com/theseed-labs/os-backend/internal/model"

	"github.com/theseed-labs/os-backend/internal/graph/gmodel"
)

// AvailableProjects is the resolver for the availableProjects field.
func (r *queryResolver) AvailableProjects(ctx context.Context) ([]*gmodel.Project, error) {
	ginCtx, err := api.GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}

	user, enforcer, db, _ := api.ForContext(ginCtx)

	ok, err := enforcer.HasRoleForUser(user.Wallet, api.RoleHall)
	if err != nil {
		return nil, err
	}

	var projects []*model.Project

	if ok {
		projects, _, err = model.ProjectModel.List(db, "open", nil, false)
		if err != nil {
			return nil, err
		}
	} else {
		projects, _, err = model.ProjectModel.ListBySponsor(db, user.Wallet, "open", nil, false)
		if err != nil {
			return nil, err
		}
	}

	return lo.Map(projects, func(g *model.Project, _ int) *gmodel.Project {
		return &gmodel.Project{
			ID:    int(g.ID),
			Logo:  g.Logo,
			Name:  g.Name,
			Intro: g.Intro,
			Desc:  g.Desc,
		}
	}), nil
}
