### Login to service with hall
POST {{host}}/v1/user/login
Content-Type: application/json

{
  "wallet": "0xEe3d9DeFdD97560c56402b3467869f293bfa35dC",
  "wallet_type": "aaaaa",
  "is_eip191_prefix": false,
  "domain": "testfoobar",
  "message": "test msg",
  "timestamp": 1,
  "signature": "1"
}

> {%
    client.global.set("auth_token", response.body.data.token);
%}


### Validate project has budgets
< {%
    client.global.set("project_id", "252")
%}
GET {{host}}/v1/projects/{{project_id}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Project has budget record", function () {
        client.assert(response.body.hasOwnProperty("data"), "Cannot find 'data' in response");
        client.assert(response.body.data.hasOwnProperty("budgets"), "Cannot find 'budgets' in response");
    });

%}


### Close project proposal with motivation greater than budget should be failed
POST {{host}}/v1/proposals/create
Authorization: Bearer {{auth_token}}

{
  "title": "测试p1提案结项请求",
  "proposal_category_id": 50,
  "vote_type": 2,
  "vote_options": null,
  "content_blocks": [
    {
      "title": "立项信息",
      "type": "preview",
      "content": "[{\"component_id\":16,\"name\":\"relate\",\"schema\":\"\",\"data\":{\"relate\":\"SIP-14003: [BetaTest] 测试p1提案立项请求\",\"proposal_id\":1512}},{\"id\":2725,\"component_id\":21,\"name\":\"budget_p1\",\"schema\":\"\",\"data\":{\"amount\":\"12345\",\"applicant\":\"0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D\",\"proposal_id\":\"os-1512\",\"typeTest\":{\"id\":1,\"name\":\"SCR\"}},\"create_ts\":1716176344},{\"id\":2726,\"component_id\":13,\"name\":\"deliverables\",\"schema\":\"\",\"data\":{\"applicant\":\"0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D\",\"description\":\"这是交付物\",\"proposal_id\":\"os-1512\"},\"create_ts\":1716176344},{\"id\":2727,\"component_id\":14,\"name\":\"deadline\",\"schema\":\"\",\"data\":{\"applicant\":\"0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D\",\"description\":\"2024-05-31T16:00:00.000Z\",\"proposal_id\":\"os-1512\"},\"create_ts\":1716176344}]"
    },
    {
      "title": "结项内容",
      "content": "这是结项内容",
      "hint": "请说明活动最终执行日期和执行效果。"
    },
    {
      "title": "交付物完成明细",
      "content": "这是交付物完成明细",
      "hint": "请详细罗列活动所有交付物的交付日期、链接和说明。"
    },
    {
      "title": "激励申请表",
      "type": "components",
      "content": "如果此项目有预付部分，请在以下表格中分配中剔除已预付的部分。",
      "name": "[\"motivation\"]"
    },
    {
      "title": "备注",
      "content": "这是备注",
      "hint": "模版中未提及但重要的内容可以在此处提及。"
    }
  ],
  "components": [
    {
      "name": "motivation",
      "data": {
        "budgetList": [
          {
            "address": "0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D",
            "assetInfo": {
              "id": 1,
              "name": "SCR"
            },
            "amount": "666666",
            "description": "asdfasdfasdf"
          }
        ]
      }
    }
  ],
  "template_id": 14,
  "create_project_proposal_id": 1512,
  "submit_to_metaforo": true,
  "metaforo_access_token": "29580|nbcr2gSKeZ1UUQcrbDDOEXqPxvir3CZhfxmHcFEk"
}

> {%
    client.test("Response should be error", function () {
        client.assert(response.status !== 200, "Response status is 200");
    });
%}

#### Verify project is still open
GET {{host}}/v1/projects/{{project_id}}

> {%
    client.test("Response should be ok", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.data.status === 'open', "project is not open state");
    });
%}


### Close project proposal with motivation less than project budget should be ok
POST {{host}}/v1/proposals/create
Authorization: Bearer {{auth_token}}

{
  "title": "测试p1提案结项请求",
  "proposal_category_id": 50,
  "vote_type": 2,
  "vote_options": null,
  "content_blocks": [
    {
      "title": "立项信息",
      "type": "preview",
      "content": "[{\"component_id\":16,\"name\":\"relate\",\"schema\":\"\",\"data\":{\"relate\":\"SIP-14003: [BetaTest] 测试p1提案立项请求\",\"proposal_id\":1512}},{\"id\":2725,\"component_id\":21,\"name\":\"budget_p1\",\"schema\":\"\",\"data\":{\"amount\":\"12345\",\"applicant\":\"0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D\",\"proposal_id\":\"os-1512\",\"typeTest\":{\"id\":1,\"name\":\"SCR\"}},\"create_ts\":1716176344},{\"id\":2726,\"component_id\":13,\"name\":\"deliverables\",\"schema\":\"\",\"data\":{\"applicant\":\"0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D\",\"description\":\"这是交付物\",\"proposal_id\":\"os-1512\"},\"create_ts\":1716176344},{\"id\":2727,\"component_id\":14,\"name\":\"deadline\",\"schema\":\"\",\"data\":{\"applicant\":\"0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D\",\"description\":\"2024-05-31T16:00:00.000Z\",\"proposal_id\":\"os-1512\"},\"create_ts\":1716176344}]"
    },
    {
      "title": "结项内容",
      "content": "这是结项内容",
      "hint": "请说明活动最终执行日期和执行效果。"
    },
    {
      "title": "交付物完成明细",
      "content": "这是交付物完成明细",
      "hint": "请详细罗列活动所有交付物的交付日期、链接和说明。"
    },
    {
      "title": "激励申请表",
      "type": "components",
      "content": "如果此项目有预付部分，请在以下表格中分配中剔除已预付的部分。",
      "name": "[\"motivation\"]"
    },
    {
      "title": "备注",
      "content": "这是备注",
      "hint": "模版中未提及但重要的内容可以在此处提及。"
    }
  ],
  "components": [
    {
      "name": "motivation",
      "data": {
        "budgetList": [
          {
            "address": "0x4564d5a8Bb409272F1FB4ae4c8b45fC0eaFd709D",
            "assetInfo": {
              "id": 1,
              "name": "SCR"
            },
            "amount": "42",
            "description": "asdfasdfasdf"
          }
        ]
      }
    }
  ],
  "template_id": 14,
  "create_project_proposal_id": 1512,
  "submit_to_metaforo": true,
  "metaforo_access_token": "29580|nbcr2gSKeZ1UUQcrbDDOEXqPxvir3CZhfxmHcFEk"
}

> {%
    client.test("Response should be ok", function () {
        client.assert(response.status === 200, "Response status is 200");
    });
%}

