// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gmodel

type Guild struct {
	ID    int    `json:"id"`
	Logo  string `json:"logo"`
	Name  string `json:"name"`
	Intro string `json:"intro"`
	Desc  string `json:"desc"`
}

type Project struct {
	ID    int    `json:"id"`
	Logo  string `json:"logo"`
	Name  string `json:"name"`
	Intro string `json:"intro"`
	Desc  string `json:"desc"`
}
