// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app_bundles": {
            "get": {
                "tags": [
                    "app_bundle"
                ],
                "summary": "List all application bundles match the query params",
                "parameters": [
                    {
                        "type": "string",
                        "description": "status of application bundle",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "which page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "size of each page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort by which field",
                        "name": "sort_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order of sort",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app_bundle.AppBundleResponseRecord"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "app_bundle"
                ],
                "summary": "List all application bundles match the query params",
                "parameters": [
                    {
                        "description": "New application bundle request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.NewAppBundleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "This api parses passed in pagination query params,",
                "tags": [
                    "project"
                ],
                "summary": "List all projects match the query params",
                "parameters": [
                    {
                        "type": "string",
                        "description": "status of project",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "which page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "size of each page",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort by which field",
                        "name": "sort_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "order of sort",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ListReplyData"
                        }
                    }
                }
            },
            "post": {
                "description": "This api create a project record with passed in data",
                "tags": [
                    "project"
                ],
                "summary": "Create a project with passed in data",
                "parameters": [
                    {
                        "description": "new project request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/:id": {
            "get": {
                "tags": [
                    "project"
                ],
                "summary": "show detail of a project",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/project.DetailReply"
                        }
                    }
                }
            },
            "put": {
                "description": "This api update a project record with passed in data",
                "tags": [
                    "project"
                ],
                "summary": "Update project information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the project",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update project info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/project.UpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/:id/add_related_proposal": {
            "post": {
                "tags": [
                    "project"
                ],
                "summary": "Add related proposals to the project",
                "parameters": [
                    {
                        "type": "number",
                        "description": "project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "proposal ID list",
                        "name": "proposalIDs",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/:id/close": {
            "post": {
                "description": "This api close specified project, admin permission is required for this operation",
                "tags": [
                    "project"
                ],
                "summary": "Close a project",
                "parameters": [
                    {
                        "type": "number",
                        "description": "project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ListReplyData": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "rows": {},
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "app_bundle.AppBundleResponseRecord": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "amount": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            }
                        }
                    }
                },
                "comment": {
                    "type": "string"
                },
                "entity": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    }
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Application"
                    }
                },
                "reviewer": {
                    "type": "string"
                },
                "season_name": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/model.ApplicationState"
                },
                "submit_date": {
                    "type": "string"
                },
                "submitter": {
                    "type": "string"
                }
            }
        },
        "model.Application": {
            "type": "object",
            "properties": {
                "applicant": {
                    "description": "Member send this application",
                    "type": "string"
                },
                "bundle_id": {
                    "type": "integer"
                },
                "comment": {
                    "description": "Comment saves some user entered data",
                    "type": "string"
                },
                "complete_message": {
                    "description": "CompleteMessage saves",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "detailed_data": {
                    "description": "DetailedData saves application detailed data\nCurrently the design is using this struct to save serialized detailed data for all applications.\nThe data will be deserialized to specified struct before using",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "detailed_type": {
                    "description": "DetailedType means a sub category of this application",
                    "type": "string"
                },
                "entity_id": {
                    "type": "integer"
                },
                "entity_type": {
                    "description": "Entity means this application's refer, which maybe project or guild.\nAnd the field EntityId is the db record ID for Project or Guild table",
                    "type": "string"
                },
                "id": {
                    "description": "unique ID for this request",
                    "type": "integer"
                },
                "reject_reason": {
                    "description": "Saves the reject reason if this application state is rejected",
                    "type": "string"
                },
                "season": {
                    "$ref": "#/definitions/model.Season"
                },
                "season_id": {
                    "description": "Season information of application",
                    "type": "integer"
                },
                "state": {
                    "description": "Application state, which contains open/approved/rejected/processing/completed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.ApplicationState"
                        }
                    ]
                },
                "type": {
                    "description": "application type",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.ApplicationType"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.ApplicationState": {
            "type": "string",
            "enum": [
                "open"
            ],
            "x-enum-varnames": [
                "ApplicationStateOpen"
            ]
        },
        "model.ApplicationType": {
            "type": "string",
            "enum": [
                "CLOSE_PROJECT",
                "NEW_REWARD"
            ],
            "x-enum-varnames": [
                "ApplicationCloseProject",
                "ApplicationNewReward"
            ]
        },
        "model.BudgetType": {
            "type": "string",
            "enum": [
                "credit"
            ],
            "x-enum-varnames": [
                "BudgetTypeCredit"
            ]
        },
        "model.NewAppBundleRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "entity": {
                    "type": "string"
                },
                "entity_id": {
                    "type": "integer"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NewApplicationRequest"
                    }
                }
            }
        },
        "model.NewApplicationRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "credit_amount": {
                    "type": "number"
                },
                "credit_asset_name": {
                    "type": "string"
                },
                "detailed_type": {
                    "type": "string"
                },
                "entity": {
                    "type": "string"
                },
                "entity_id": {
                    "type": "integer"
                },
                "target_user_wallet": {
                    "type": "string"
                },
                "token_amount": {
                    "type": "number"
                },
                "token_asset_name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.ProjectBudget": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "description": "project_id",
                    "type": "integer"
                },
                "remain_amount": {
                    "description": "remain_amount",
                    "type": "number"
                },
                "total_amount": {
                    "description": "total_amount = used_amount + remain_amount",
                    "type": "number"
                },
                "type": {
                    "description": "budget type, credit or token",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.BudgetType"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "used_amount": {
                    "description": "used_amount",
                    "type": "number"
                }
            }
        },
        "model.ProjectStatus": {
            "type": "string",
            "enum": [
                "open"
            ],
            "x-enum-varnames": [
                "ProjectStatusOpen"
            ]
        },
        "model.Season": {
            "type": "object",
            "properties": {
                "endAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "startAt": {
                    "description": "TODO: This field do not contains timezone info, need to review code about this",
                    "type": "string"
                }
            }
        },
        "model.SpecialProjectType": {
            "type": "string",
            "enum": [
                "city_hall"
            ],
            "x-enum-varnames": [
                "SpecialProjectCityHall"
            ]
        },
        "project.BudgetParam": {
            "type": "object",
            "properties": {
                "budget_type": {
                    "$ref": "#/definitions/model.BudgetType"
                },
                "name": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "project.CreateReq": {
            "type": "object",
            "properties": {
                "budgets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/project.BudgetParam"
                    }
                },
                "desc": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "logo": {
                    "description": "base64 encoded image string",
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "proposals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sponsors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "project.DetailReply": {
            "type": "object",
            "properties": {
                "budgets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ProjectBudget"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "is_special": {
                    "type": "boolean"
                },
                "logo": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "proposals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "special_type": {
                    "$ref": "#/definitions/model.SpecialProjectType"
                },
                "sponsors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "Status may have those values: open/pending_close/closed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.ProjectStatus"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "project.UpdateReq": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://test-api.seedao.tech",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "OS Backend API service",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
